fix checking working directory

diff --git a/otp_build b/otp_build
--- a/otp_build
+++ b/otp_build
@@ -1111,25 +1111,28 @@ do_update_gdb_tools ()
 {
     get_do_commit $1
 
-    if [ -z "$(git status --porcelain --untracked-files=no)" ]
+    if [ $do_commit = true ] && test -n "$(git status --porcelain --untracked-files=no)"
     then
+        echo "'otp_build update_gdb_tools' will create a commit."
+        echo "Git's working directory is not clean."
+        echo "Please stash or commit the working directory before proceeding."
+        exit 1
+    fi
 
-        (do_download_gdb_tools) || {
-            echo "Downloading gdb_tools failed. Please check your source tree, and report this error."
-            exit 1
-        }
-        out_files=
+    (do_download_gdb_tools) || {
+        echo "Downloading gdb_tools failed. Please check your source tree, and report this error."
+        exit 1
+    }
 
-        echo "Successfully updated gdb_tools"
-        if [ $do_commit != true ]; then
-            echo "Updated: make/gdb_tools_vsn make/jit-reader.c.sha256sum"
-        else
-            set_common_vars
-            git add "$ERL_TOP/make/gdb_tools_vsn" $ERL_TOP/make/jit-reader.c.sha256sum $ERL_TOP/make/jit-reader.h.sha256sum > /dev/null
-            git commit -m  "Updated gdb_tools version to $GDB_TOOLS_VSN" > /dev/null
-        fi
+    out_files=  # why is this needed. it was needed for elixir
+
+    echo "Successfully updated gdb_tools"
+    if [ $do_commit != true ]; then
+        echo "Updated: make/gdb_tools_vsn make/jit-reader.c.sha256sum"
     else
-        echo "Git's working directory is not clean. Please stash or commit the working directory before proceeding."
+        set_common_vars
+        git add "$ERL_TOP/make/gdb_tools_vsn" $ERL_TOP/make/jit-reader.c.sha256sum $ERL_TOP/make/jit-reader.h.sha256sum > /dev/null
+        git commit -m  "Updated gdb_tools version to $GDB_TOOLS_VSN" > /dev/null
     fi
 }
 
@@ -1483,7 +1486,7 @@ case "$1" in
         download_gdb_tools)
             do_download_gdb_tools;;
         update_gdb_tools)
-            do_update_gdb_tools;;
+            do_update_gdb_tools $2;;
         download_ex_doc)
                 do_download_ex_doc;;
         update_ex_doc)
