final fixes

diff --git a/otp_build b/otp_build
--- a/otp_build
+++ b/otp_build
@@ -1054,7 +1054,7 @@ set_common_vars() {
     GDB_REPO="git@github.com:erlang/otp-gdb-utils.git"
 
     # Version of gdb-tools to download
-    GDB_TOOLS_VSN=
+    GDB_TOOLS_VSN=$(cat "$GDB_TOOLS_VSN_PATH/gdb_tools_vsn" | cut -d- -f2)
 
     # SHASUM_FORMAT has values: sha256sum, sha1sum, shasum
     SHASUM_FORMAT=
@@ -1065,41 +1065,31 @@ set_common_vars() {
 
 set_default_gdb_tools_version ()
 {
-    if find "$GDB_TOOLS_VSN_PATH" -name gdb_tools_vsn | grep -q "."
+    GDB_TOOLS_VSN=$(cat "$GDB_TOOLS_VSN_PATH/gdb_tools_vsn" | cut -d- -f2)
+    echo "Current GDB_TOOLS_VSN: $GDB_TOOLS_VSN and OTP_VERSION: $OTP_VERSION"
+    if git ls-remote --heads "$GDB_REPO" "maint-$OTP_VERSION" | grep -q "." > /dev/null
     then
-        GDB_TOOLS_VSN=$(cat "$GDB_TOOLS_VSN_PATH/gdb_tools_vsn")
+        # Set the GDB_TOOL version to install, if OTP_VERSION exists as a branch
+        GDB_TOOLS_VSN=maint-$OTP_VERSION
     else
-        GDB_TOOLS_VSN="maint-$OTP_VERSION"
+        # OTP_VERSION does not exists as a branch, which means that possibly
+        # OTP_VERSION e.g., 28, is compatible with gdb_tools 27, since there is no change.
+        GDB_TOOLS_VSN=$(git ls-remote --heads -q git@github.com:erlang/otp-gdb-utils.git \
+            | grep . | cut -f2 | cut -d/ -f3 | sort -r | head -n1)
     fi
+    displayed_gdb_vsn=$(echo "$GDB_TOOLS_VSN" | cut -d- -f2)
+    echo "Updated GDB_TOOLS_VSN: $displayed_gdb_vsn and OTP_VERSION: $OTP_VERSION"
 }
 
 clone_gdb_tools ()
 {
-    echo "Downloading gdb-tools (version $GDB_TOOLS_VSN) for Erlang/OTP ($OTP_VERSION)"
-    # download OTP_VERSION or latest
-    if find "$ERL_TOP" -name jit-reader.c | grep -q "." > /dev/null
-    then
-        # Set the GDB_TOOL version to install
-        if (cd "$GDB_TOOLS_INSTALL_PATH" && git ls-remote --heads "$GDB_REPO" "maint-$OTP_VERSION" | grep -q "." > /dev/null)
-        then
-            GDB_TOOLS_VSN=maint-$OTP_VERSION
-        else
-            # choose the lastest version available
-            GDB_TOOLS_VSN=$("cd $GDB_TOOLS_INSTALL_PATH && git branch | sort -r | head -n1")
-        fi
-        echo "git clone -b $GDB_TOOLS_VSN $GDB_REPO $GDB_TOOLS_INSTALL_PATH"
-        (cd "$GDB_TOOLS_INSTALL_PATH" && git fetch origin && git switch -C "$GDB_TOOLS_VSN" > /dev/null 2>&1) || {
-            echo "Downloading gdb_tools failed. Please check your source tree."
-            exit 1
+    echo "Downloading gdb-tools for Erlang/OTP $OTP_VERSION"
+    echo "git clone -b $GDB_TOOLS_VSN $GDB_REPO $GDB_TOOLS_INSTALL_PATH"
+    (git clone -b "$GDB_TOOLS_VSN" "$GDB_REPO" "$GDB_TOOLS_INSTALL_PATH" > /dev/null 2>&1 )  || {
+        echo "Downloading gdb_tools failed. Please check your source tree, and report this error."
+        exit 1
         }
-    else
-        echo "git clone -b $GDB_TOOLS_VSN $GDB_REPO $GDB_TOOLS_INSTALL_PATH"
-        (git clone -b "$GDB_TOOLS_VSN" "$GDB_REPO" "$GDB_TOOLS_INSTALL_PATH" > /dev/null 2>&1 )  || {
-            echo "Downloading gdb_tools failed. Please check your source tree."
-            exit 1
-        }
-    fi
-    echo "Downloaded gdb-tools v$GDB_TOOLS_VSN for Erlang/OTP $OTP_VERSION"
+    echo "Downloaded gdb-tools for Erlang/OTP $OTP_VERSION"
 }
 
 clean_file ()
@@ -1119,23 +1109,19 @@ set_otp_version ()
 
 do_update_gdb_tools ()
 {
-    do_download_gdb_tools
-    #     if do_download_gdb_tools; then
+    (do_download_gdb_tools) || {
+        echo "Downloading gdb_tools failed. Please check your source tree, and report this error."
+        exit 1
+    }
+    out_files=
 
-    #         out_files=
-
-    #         echo "Successfully updated gdb_tools"
-    #         if [ $do_commit != true ]; then
-    #             echo "Updated: make/gdb_tools_vsn make/jit-reader.c.sha256sum"
-    #         else
-    #             git add "$ERL_TOP/make/gdb_tools_vsn"  $ERL_TOP/make/jit-reader.c.sha256sum $ERL_TOP/make/jit-reader.h.sha256sum
-    #             git commit -m  "Updated gdb_tools version to ${GDB_TOOLS_VSN}"
-    #         fi
-    #     fi
-    # else
-    #     echo "You need to have both sha1sum and sha256sum installed to update gdb_tools_vsn"
-    #     exit 1
-    # fi
+    echo "Successfully updated gdb_tools"
+    if [ $do_commit != true ]; then
+        echo "Updated: make/gdb_tools_vsn make/jit-reader.c.sha256sum"
+    else
+        git add "$ERL_TOP/make/gdb_tools_vsn" $ERL_TOP/make/jit-reader.c.sha256sum $ERL_TOP/make/jit-reader.h.sha256sum
+        git commit -m  "Updated gdb_tools version to ${GDB_TOOLS_VSN}"
+    fi
 }
 
 # $1: jit-reader.c, jit-reader.h, etc
