Win CI

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -523,7 +523,6 @@ jobs:
 
       - name: Run tests
         id: run-tests
-        if: ${{ !cancelled() }}
         run: |
           set -x
           unzip -q tests.zip
@@ -544,8 +543,12 @@ jobs:
             debug) echo "No debug tests on windows" ;;
             *) cd release/tests/test_server
                erl.exe -emu_type $TYPE -noshell -eval "ts:install()" -eval "ts:run($APP,[batch])" -s init stop
+               cd -
                ;;
           esac
+          ERROR_CNT=$(grep "^=result        failed:" release/tests/test_server/ct_run.*/tests.*.logs/run*/suite.log | wc -l)
+          echo "$ERROR_CNT testcases failed!"
+          exit "$ERROR_CNT"
 
       - name: Cleanup tests
         if: ${{ !cancelled() }}
