Fix windows make test and add windows testing to github actions

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -215,6 +215,166 @@ jobs:
     with:
       base_branch:              ${{ needs.setup.outputs.base_branch }}
 
+  test-windows:
+    name: Test Win64 Erlang/OTP
+    needs: [pack, build-windows]
+    defaults:
+      run:
+        shell: wsl-bash {0}
+    runs-on: windows-2022
+    if: needs.pack.outputs.changes != '[]'
+    strategy:
+      matrix:
+        # type: ${{ fromJson(needs.pack.outputs.all) }}
+        type: ${{ fromJson(needs.pack.outputs.changes) }}
+        # type: ["os_mon","sasl"]
+      fail-fast: false
+    steps:
+      - uses: Vampire/setup-wsl@v3.1.1
+        with:
+          distribution: Ubuntu-18.04
+      - name: Install WSL dependencies
+        run: apt update && apt install -y g++-mingw-w64 gcc-mingw-w64 make autoconf unzip zip
+      - name: Download installer
+        uses: actions/download-artifact@v4.1.8
+        with:
+          name: otp_win32_installer
+      - name: Download tests
+        uses: actions/download-artifact@v4.1.8
+        with:
+          name: otp_tests
+
+      - name: Install OTP
+        shell: cmd
+        run: |
+            echo %cd%
+            start "" /WAIT ${{ needs.build-windows.outputs.installer_name }} /S /D=%CD%\release\win32\
+            dir %cd%
+            dir %cd%\release\win32\
+
+      - name: Download source archive
+        uses: actions/download-artifact@v4.1.8
+        with:
+          name: otp_prebuilt
+
+      - name: Run tests
+        id: run-tests
+        run: |
+          set -x
+          unzip -q tests.zip
+
+          tar -xzf ./otp_src.tar.gz
+
+          export ERL_TOP="$(pwd)/otp"
+          export MAKEFLAGS=-j$(($(nproc) + 2))
+
+          eval `./otp/otp_build env_win32 x64`
+
+          export PATH=`pwd`/release/win32/bin/:$PATH
+
+          APP="${{ matrix.type }}"
+          TYPE=opt
+          ## Need to specialize for epmd, emulator and debug
+          case "${APP}" in
+            debug)
+               echo "No debug tests on windows"
+               ;;
+            *)
+               (cd release/tests/test_server && erl.exe -emu_type $TYPE -noshell -eval "ts:install()" -eval "ts:run($APP,[batch])" -s init stop)
+               if grep "^=result[ ]*failed:" release/tests/test_server/ct_run.*/tests.${APP}_test.logs/run*/suite.log; then
+                  exit 1
+               fi
+               ;;
+          esac
+
+      - name: Cleanup tests
+        if: ${{ !cancelled() && matrix.type != 'debug' }}
+        run: tar czf ${{ matrix.type }}_win32_test_results.tar.gz release/tests/test_server
+      - name: Upload test results
+        uses: actions/upload-artifact@v4.4.0
+        if: ${{ !cancelled() && matrix.type != 'debug' }}
+        with:
+          name: ${{ matrix.type }}_win32_test_results
+          path: ${{ matrix.type }}_win32_test_results.tar.gz
+
+  system-test-windows:
+    name: Test Win64 Erlang/OTP (system)
+    defaults:
+      run:
+        shell: wsl-bash {0}
+    runs-on: windows-2022
+    if: ${{ !cancelled() }} # Run even if the need has failed
+    needs: [test-windows, build-windows]
+    steps:
+      - uses: Vampire/setup-wsl@v3.1.1
+        with:
+          distribution: Ubuntu-18.04
+      - name: Install WSL dependencies
+        run: apt update && apt install -y g++-mingw-w64 gcc-mingw-w64 make autoconf unzip zip
+      - name: Download installer
+        uses: actions/download-artifact@v4.1.8
+        with:
+          name: otp_win32_installer
+      - name: Download tests
+        uses: actions/download-artifact@v4.1.8
+        with:
+          name: otp_tests
+
+      - name: Install OTP
+        shell: cmd
+        run: |
+            echo %cd%
+            start "" /WAIT ${{ needs.build-windows.outputs.installer_name }} /S /D=%CD%\release\win32\
+            dir %cd%
+            dir %cd%\release\win32\
+
+      - name: Download source archive
+        uses: actions/download-artifact@v4.1.8
+        with:
+          name: otp_prebuilt
+
+      - name: Download test results
+        uses: actions/download-artifact@v4.1.8
+      - name: Merge test results
+        run: |
+          shopt -s nullglob
+          for file in *_win32_test_results/*.tar.gz; do
+            tar xvzf $file
+          done
+          export PATH=`pwd`/release/win32/bin/:$PATH
+          cd release/tests/test_server && ct_run.exe -noshell -refresh_logs $(wslpath -w `pwd`)
+
+      - name: Run system tests
+        run: |
+          set -x
+          unzip -q -o tests.zip
+
+          tar -xzf ./otp_src.tar.gz
+
+          export ERL_TOP="$(pwd)/otp"
+          export MAKEFLAGS=-j$(($(nproc) + 2))
+
+          eval `./otp/otp_build env_win32 x64`
+
+          export PATH=`pwd`/release/win32/bin/:$PATH
+
+          (cd release/tests/test_server && erl.exe -noshell -eval "ts:install()" -eval "ts:run(system,[batch])" -s init stop)
+          if grep "^=result[ ]*failed:" release/tests/test_server/ct_run.*/tests.system_test.logs/run*/suite.log; then
+               exit 1
+          fi
+
+      - name: Cleanup tests
+        if: ${{ !cancelled() }}
+        run: |
+          tar czf test_results_win32.tar.gz release/tests/test_server
+          
+      - name: Upload test results
+        uses: actions/upload-artifact@v4.4.0
+        if: ${{ !cancelled() }}
+        with:
+          name: test_results_win32
+          path: test_results_win32.tar.gz
+
   test:
     name: Test Erlang/OTP
     needs: pack
